"""
Django settings for todo_orchestrator project.

Generated by 'django-admin startproject' using Django 4.2.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "django-insecure-your-secret-key-here-change-in-production"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not os.environ.get("RENDER", False)

# Allow all Render.com subdomains in production, specific hosts in development
if os.environ.get("RENDER"):
    ALLOWED_HOSTS = [
        ".onrender.com",  # Allow all Render subdomains
        "localhost",
        "127.0.0.1",
    ]
else:
    # Development settings
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_bootstrap5",
    "corsheaders",
    "testing",  # Our testing orchestration app
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files on Render
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "todo_orchestrator.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "todo_orchestrator.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for static file serving on Render
if os.environ.get("RENDER"):
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings for API testing
if os.environ.get("RENDER"):
    # Production CORS settings - FastAPI on same host
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:8002",  # FastAPI on orchestrator port
        "http://127.0.0.1:8002",
    ]
    CORS_ALLOW_ALL_ORIGINS = False
else:
    # Development CORS settings
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:8002",  # FastAPI server on orchestrator port
        "http://127.0.0.1:8002",
    ]
    CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all origins in debug mode

# Custom settings for FastAPI integration
if os.environ.get("RENDER"):
    # Production - FastAPI runs on same host, different port
    FASTAPI_SERVER_URL = "http://localhost:8002"  # Orchestrator's FastAPI port
else:
    FASTAPI_SERVER_URL = (
        "http://localhost:8002"  # Avoid conflict with todo-display (port 8000)
    )

FASTAPI_PROJECT_PATH = (
    "../fastapi/todo-api"  # Relative path to FastAPI project from web-frameworks
)

# CSRF settings for production deployment
if os.environ.get("RENDER"):
    CSRF_TRUSTED_ORIGINS = [
        "https://*.onrender.com",
    ]
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_HTTPONLY = False
    # Ensure session cookies are secure in production
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "Lax"
else:
    # Development CSRF settings
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:8001",
        "http://127.0.0.1:8001",
    ]
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False

# Additional CSRF settings for Django 4.0+ compatibility
CSRF_USE_SESSIONS = False
CSRF_COOKIE_AGE = 31449600  # 1 year

# Bootstrap settings
BOOTSTRAP5 = {
    "css_url": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css",
    "javascript_url": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js",
}
