# Generated by Django 6.0.4 on 2026-04-19 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APITestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('endpoint', models.CharField(max_length=200)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('execution_time', models.FloatField(help_text='Execution time in seconds')),
            ],
            options={
                'verbose_name': 'API Test History',
                'verbose_name_plural': 'API Test Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('pid', models.IntegerField(blank=True, help_text='Process ID of running server', null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('port', models.IntegerField(default=8000)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Server Status',
                'verbose_name_plural': 'Server Status',
            },
        ),
    ]
